version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: djangogames
    container_name: djangogames
    environment:
      POSTGRES_HOST: "host.docker.internal"
    volumes:
      - .:/app:z
      - ./collected_static:/app/djangogames/collected_static
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    ports:
      - "1234:1234"
    command: /start
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning